### ISSUE TITLE
Static code analysis

### ISSUE THREAD

**Issue by kovacsge11** [BME-MIT-IET/Padlizsan-emoji-iet-2018#2]

**Comment by kovacsge11** [comment]
Did static code review for .py files, which were cut out from the ipynb files. I was using SonarQube for the analysis. Found minor code smell issues: two unused variables and some variables which weren't named according to the python convention/regex.

**Comment by kovacsge11** [comment]
Found one more unused variable and new bad variable namings.

**Comment by kovacsge11** [comment]
Created wiki page for the solution of this issue.

**Comment by aliras1** [comment]
Can we now close this issue?
